name: GPW Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 7-16 * * 1-5"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalacja bibliotek
        run: pip install -r requirements.txt

      - name: Uruchomienie bota
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python main.py
